name: Codeception Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DEFAULT_COMPOSER_FLAGS: "--no-interaction --no-ansi --no-progress --no-suggest"
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4.2
          extensions: mbstring, intl, gd, imagick, zip, dom, mysql, pdo, pdo_mysql, fileinfo

      - run: composer install

      - name: Prepare the application
        run: cp .github/workflows/.env.mysql tests/.env

      - run: vendor/bin/codecept run
        env:
          SECURITY_KEY: abcde12345
          DEFAULT_SITE_URL: http://snipcart-craft-plugin.test/index.php
          FROM_EMAIL_NAME: Craft CMS
          FROM_EMAIL_ADDRESS: info@craftcms.com
